var annotated_dup =
[
    [ "paxg", "namespacepaxg.html", [
      [ "Circle", "structpaxg_1_1Circle.html", "structpaxg_1_1Circle" ],
      [ "Color", "structpaxg_1_1Color.html", "structpaxg_1_1Color" ],
      [ "IDrawable", "structpaxg_1_1IDrawable.html", "structpaxg_1_1IDrawable" ],
      [ "Image", "structpaxg_1_1Image.html", "structpaxg_1_1Image" ],
      [ "Rect", "structpaxg_1_1Rect.html", "structpaxg_1_1Rect" ],
      [ "String", "structpaxg_1_1String.html", "structpaxg_1_1String" ],
      [ "Texture", "structpaxg_1_1Texture.html", "structpaxg_1_1Texture" ],
      [ "Vec2", "structpaxg_1_1Vec2.html", "structpaxg_1_1Vec2" ],
      [ "Vec2f", "structpaxg_1_1Vec2f.html", "structpaxg_1_1Vec2f" ]
    ] ],
    [ "paxs", "namespacepaxs.html", [
      [ "cal", "namespacepaxs_1_1cal.html", [
        [ "SimulationSteps", "classpaxs_1_1cal_1_1SimulationSteps.html", "classpaxs_1_1cal_1_1SimulationSteps" ],
        [ "CalBP", "classpaxs_1_1cal_1_1CalBP.html", "classpaxs_1_1cal_1_1CalBP" ],
        [ "IslamicDate", "classpaxs_1_1cal_1_1IslamicDate.html", "classpaxs_1_1cal_1_1IslamicDate" ],
        [ "GregorianDate", "classpaxs_1_1cal_1_1GregorianDate.html", "classpaxs_1_1cal_1_1GregorianDate" ],
        [ "JulianDate", "classpaxs_1_1cal_1_1JulianDate.html", "classpaxs_1_1cal_1_1JulianDate" ],
        [ "JapanDate", "classpaxs_1_1cal_1_1JapanDate.html", "classpaxs_1_1cal_1_1JapanDate" ],
        [ "JulianDayNumber", "classpaxs_1_1cal_1_1JulianDayNumber.html", "classpaxs_1_1cal_1_1JulianDayNumber" ]
      ] ],
      [ "JapaneseEra", "structpaxs_1_1JapaneseEra.html", "structpaxs_1_1JapaneseEra" ],
      [ "RGBA", "structpaxs_1_1RGBA.html", "structpaxs_1_1RGBA" ],
      [ "RyoseikokuColor", "structpaxs_1_1RyoseikokuColor.html", "structpaxs_1_1RyoseikokuColor" ],
      [ "SoilTemp", "structpaxs_1_1SoilTemp.html", "structpaxs_1_1SoilTemp" ],
      [ "File", "structpaxs_1_1File.html", null ],
      [ "Grid3x3", "structpaxs_1_1Grid3x3.html", "structpaxs_1_1Grid3x3" ],
      [ "Elevation", "classpaxs_1_1Elevation.html", null ],
      [ "GraphicVisualizationList", "classpaxs_1_1GraphicVisualizationList.html", "classpaxs_1_1GraphicVisualizationList" ],
      [ "Logger", "classpaxs_1_1Logger.html", "classpaxs_1_1Logger" ],
      [ "MercatorDeg", "structpaxs_1_1MercatorDeg.html", "structpaxs_1_1MercatorDeg" ],
      [ "EquirectangularDeg", "structpaxs_1_1EquirectangularDeg.html", "structpaxs_1_1EquirectangularDeg" ],
      [ "MapProjection", "classpaxs_1_1MapProjection.html", null ],
      [ "MapUtility", "structpaxs_1_1MapUtility.html", null ],
      [ "Math", "classpaxs_1_1Math.html", null ],
      [ "Agent", "classpaxs_1_1Agent.html", "classpaxs_1_1Agent" ],
      [ "Data", "classpaxs_1_1Data.html", "classpaxs_1_1Data" ],
      [ "Environment", "classpaxs_1_1Environment.html", "classpaxs_1_1Environment" ],
      [ "Human", "classpaxs_1_1Human.html", "classpaxs_1_1Human" ],
      [ "Object", "classpaxs_1_1Object.html", "classpaxs_1_1Object" ],
      [ "Simulator", "classpaxs_1_1Simulator.html", "classpaxs_1_1Simulator" ],
      [ "Graphics3DModel", "classpaxs_1_1Graphics3DModel.html", "classpaxs_1_1Graphics3DModel" ],
      [ "KoyomiSiv3D", "classpaxs_1_1KoyomiSiv3D.html", "classpaxs_1_1KoyomiSiv3D" ],
      [ "PaxSapienticaInitSiv3D", "classpaxs_1_1PaxSapienticaInitSiv3D.html", null ],
      [ "BaseKey", "structpaxs_1_1BaseKey.html", "structpaxs_1_1BaseKey" ],
      [ "Key", "classpaxs_1_1Key.html", "classpaxs_1_1Key" ],
      [ "Coordinate", "classpaxs_1_1Coordinate.html", "classpaxs_1_1Coordinate" ],
      [ "MapView", "classpaxs_1_1MapView.html", "classpaxs_1_1MapView" ],
      [ "SelectLanguage", "classpaxs_1_1SelectLanguage.html", "classpaxs_1_1SelectLanguage" ],
      [ "Language", "classpaxs_1_1Language.html", "classpaxs_1_1Language" ],
      [ "LocationPoint", "structpaxs_1_1LocationPoint.html", "structpaxs_1_1LocationPoint" ],
      [ "PlaceNameLocation", "classpaxs_1_1PlaceNameLocation.html", "classpaxs_1_1PlaceNameLocation" ],
      [ "AgentLocation", "classpaxs_1_1AgentLocation.html", "classpaxs_1_1AgentLocation" ],
      [ "LocationRange", "structpaxs_1_1LocationRange.html", "structpaxs_1_1LocationRange" ],
      [ "TextureLocation", "classpaxs_1_1TextureLocation.html", "classpaxs_1_1TextureLocation" ],
      [ "MapViewerSiv3D", "classpaxs_1_1MapViewerSiv3D.html", "classpaxs_1_1MapViewerSiv3D" ],
      [ "Pulldown", "classpaxs_1_1Pulldown.html", "classpaxs_1_1Pulldown" ],
      [ "MenuBar", "classpaxs_1_1MenuBar.html", "classpaxs_1_1MenuBar" ],
      [ "StringViewerSiv3D", "classpaxs_1_1StringViewerSiv3D.html", "classpaxs_1_1StringViewerSiv3D" ],
      [ "XYZTile", "classpaxs_1_1XYZTile.html", "classpaxs_1_1XYZTile" ],
      [ "StatusDisplayer", "structpaxs_1_1StatusDisplayer.html", null ],
      [ "StringExtensions", "structpaxs_1_1StringExtensions.html", null ],
      [ "TouchManager", "structpaxs_1_1TouchManager.html", "structpaxs_1_1TouchManager" ],
      [ "Vector2", "structpaxs_1_1Vector2.html", "structpaxs_1_1Vector2" ]
    ] ],
    [ "s3d", "namespaces3d.html", [
      [ "detail", "namespaces3d_1_1detail.html", [
        [ "Console_impl", "classs3d_1_1detail_1_1Console__impl.html", "classs3d_1_1detail_1_1Console__impl" ]
      ] ],
      [ "Point", "structs3d_1_1Point.html", "structs3d_1_1Point" ],
      [ "Vec2", "structs3d_1_1Vec2.html", "structs3d_1_1Vec2" ],
      [ "ColorF", "classs3d_1_1ColorF.html", "classs3d_1_1ColorF" ],
      [ "Color", "classs3d_1_1Color.html", "classs3d_1_1Color" ],
      [ "Rect", "structs3d_1_1Rect.html", "structs3d_1_1Rect" ],
      [ "Line", "classs3d_1_1Line.html", "classs3d_1_1Line" ],
      [ "Model", "classs3d_1_1Model.html", "classs3d_1_1Model" ],
      [ "Image", "classs3d_1_1Image.html", "classs3d_1_1Image" ],
      [ "Graphics", "classs3d_1_1Graphics.html", null ],
      [ "Vec3", "classs3d_1_1Vec3.html", "classs3d_1_1Vec3" ],
      [ "DebugCamera3D", "classs3d_1_1DebugCamera3D.html", "classs3d_1_1DebugCamera3D" ],
      [ "Graphics3D", "classs3d_1_1Graphics3D.html", null ],
      [ "Scene", "classs3d_1_1Scene.html", null ],
      [ "Key", "classs3d_1_1Key.html", null ],
      [ "Input", "classs3d_1_1Input.html", null ],
      [ "Window", "classs3d_1_1Window.html", null ],
      [ "System", "classs3d_1_1System.html", null ],
      [ "Circle", "structs3d_1_1Circle.html", "structs3d_1_1Circle" ],
      [ "FontMethod", "classs3d_1_1FontMethod.html", "classs3d_1_1FontMethod" ],
      [ "Font", "classs3d_1_1Font.html", "classs3d_1_1Font" ],
      [ "Mouse", "classs3d_1_1Mouse.html", null ],
      [ "Texture", "classs3d_1_1Texture.html", "classs3d_1_1Texture" ],
      [ "Triangle", "structs3d_1_1Triangle.html", "structs3d_1_1Triangle" ],
      [ "Ellipse", "structs3d_1_1Ellipse.html", "structs3d_1_1Ellipse" ],
      [ "Sound", "classs3d_1_1Sound.html", "classs3d_1_1Sound" ],
      [ "Unicode", "classs3d_1_1Unicode.html", null ],
      [ "Quaternion", "classs3d_1_1Quaternion.html", "classs3d_1_1Quaternion" ],
      [ "Sphere", "classs3d_1_1Sphere.html", "classs3d_1_1Sphere" ],
      [ "MSRenderTexture", "classs3d_1_1MSRenderTexture.html", "classs3d_1_1MSRenderTexture" ],
      [ "ScopedRenderTarget3D", "classs3d_1_1ScopedRenderTarget3D.html", "classs3d_1_1ScopedRenderTarget3D" ],
      [ "ScopedRenderStates3D", "classs3d_1_1ScopedRenderStates3D.html", "classs3d_1_1ScopedRenderStates3D" ],
      [ "RenderTexture", "classs3d_1_1RenderTexture.html", "classs3d_1_1RenderTexture" ],
      [ "ScopedRenderStates2D", "classs3d_1_1ScopedRenderStates2D.html", "classs3d_1_1ScopedRenderStates2D" ],
      [ "ScopedRenderTarget2D", "classs3d_1_1ScopedRenderTarget2D.html", "classs3d_1_1ScopedRenderTarget2D" ],
      [ "TextStyle", "classs3d_1_1TextStyle.html", null ],
      [ "SimpleHTTP", "classs3d_1_1SimpleHTTP.html", "classs3d_1_1SimpleHTTP" ],
      [ "Array", "classs3d_1_1Array.html", "classs3d_1_1Array" ],
      [ "Mat3x2", "classs3d_1_1Mat3x2.html", null ],
      [ "Transformer2D", "classs3d_1_1Transformer2D.html", "classs3d_1_1Transformer2D" ],
      [ "RoundRect", "classs3d_1_1RoundRect.html", "classs3d_1_1RoundRect" ],
      [ "Shader", "classs3d_1_1Shader.html", null ],
      [ "SimpleGUI", "classs3d_1_1SimpleGUI.html", null ],
      [ "Spline2D", "classs3d_1_1Spline2D.html", "classs3d_1_1Spline2D" ]
    ] ]
];