name: CMake-All-Build

on:
  push:
    branches: [ main, develop ]
  pull_request:

env:
  BUILD_TYPE: Debug
  WORK_SPACE: ${{github.workspace}}/Projects

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive ExternalLibrary/googletest
        git submodule update --init --recursive ExternalLibrary/stb

    - name: Install dependencies
      run: |
        sudo apt-get clean
        sudo apt-get update
        sudo apt-get install libopencv-dev
        sudo apt-get install cmake

    - name: Configure CMake
      run: |
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.WORK_SPACE}} -G "Unix Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all -j 12
