name: CMake-Unit-Test

on:
  pull_request:

env:
  BUILD_TYPE: Debug
  WORK_SPACE: ${{github.workspace}}/Projects
  TEST_DIR: UnitTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive ExternalLibrary/googletest
        git submodule update --init --recursive ExternalLibrary/stb

    - name: Install dependencies
      run: |
        sudo apt-get clean
        sudo apt-get update
        sudo apt-get install libsfml-dev
        sudo apt-get install cmake

    - name: Configure CMake
      run: |
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.WORK_SPACE}}/${{env.TEST_DIR}} -G "Unix Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all -j 12

    - name: Run tests 
      run: |
        cd ${{env.WORK_SPACE}}/${{env.TEST_DIR}}/bin/
        for file in *; do
          if [[ -x "$file" ]]; then
            ./"$file"
          fi
        done
