name: CMake-CUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug
  WORK_SPACE: ${{github.workspace}}/Project/GeographicDataToSimulationGrid
  TARGET: ImageCombine

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install opencv
      run: |
        sudo apt install libopencv-dev
        sudo apt install cmake
        sudo apt install g++

    - name: Configure CMake
      run: |
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.WORK_SPACE}} -G "Unix Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.TARGET}} -- -j 12

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Build-Results
        path: ${{env.WORK_SPACE}}/bin
