name: Generate-Doxygen

on:
  push:
    branches:
      - main

env:
    DOXYGEN_DOCS: ${{github.workspace}}/Documents/Doxygen

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Doxygen and Graphviz
      run: sudo apt-get install doxygen graphviz

    - name: Generate Documentation
      run: |
        cd $DOXYGEN_DOCS
        doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        branch: gh-pages
        folder: $DOXYGEN_DOCS/html
